name: flutter_recruitment_task
description: Flutter recruitment task.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  auto_route: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  auto_route_generator: ^2.4.0
  json_serializable: ^5.0.2

flutter:
  uses-material-design: true
